import turtle
t=turtle.Turtle()
t.penup()
t.goto(0,200)
t.write('Geometry : Trigonal Planar ',font=('Calibri',28,'bold'))
t.goto(0,150)
t.write("Shape : Trigonal Planar ",font=('Calibri',28,'bold'))
t.goto(-58,-5)
t.write("B")
t.goto(-50,0)
t.pendown()
t.forward(100)
t.write('B')
t.penup()
t.left(120)
t.pendown()
t.forward(100)
t.write('B')
t.penup()
t.left(120)
t.pendown()
t.forward(100)
t.penup()
t.goto(0,33.33)
t.write("A")
t.left(120+40)
t.goto(-50,0)
t.pendown()
t.forward(60)
t.penup()
t.goto(0,45)
t.left(50)
t.pendown()
t.forward(45)
t.penup()
t.goto(5,35)
t.right(90+40)
t.pendown()
t.forward(55)
t.hideturtle()

